version: "3.8"

services:
  radio_bot:
    container_name: radio_bot
    build: ./
    image: radio_bot_image
    restart: always
    command: python /app/main.py
    depends_on:
      lavalink:
        condition: service_healthy

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: my_lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=Qwert*9
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      # - ./plugins/:/opt/Lavalink/plugins/
    ports:
      - 2333:2333

    healthcheck:
      test: ["CMD", "wget", "--header", "Authorization: Qwert*9", "http://lavalink:2333/version"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
